### ISSUE TITLE
Test case for Kannada 6

### ISSUE THREAD

**Issue by MayuraVerma** [unicode-org/text-rendering-tests#20] opened 2017-03-07 12:45 UTC
ಜಿ಼ೕಬೆನ್ 

the above is discontinuous with coretext but correct in harfbuzz

**Comment by brawer** [comment] 2017-03-07 14:15
Duplicate of https://github.com/unicode-org/text-rendering-tests/issues/22.

**Closed by brawer** 2017-03-07 14:15 UTC

**Comment by MayuraVerma** [comment] 2017-03-07 15:28
Apple bugreport: 27837509
